# Generated by Django 3.0.4 on 2020-03-30 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics')),
                ('bio', models.TextField(blank=True, default=' ', max_length=200, null=True)),
                ('email', models.EmailField(max_length=70)),
                ('ac_type', models.CharField(choices=[('Individual', 'Individual'), ('Organization', 'Organization')], default=' ', max_length=12)),
                ('address', models.CharField(max_length=200, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('followers', models.ManyToManyField(blank=True, related_name='followers_profile', to='accounts.UserProfile')),
                ('following', models.ManyToManyField(blank=True, related_name='following_profile', to='accounts.UserProfile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
