# Generated by Django 3.0.5 on 2020-05-18 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_connected',
            new_name='author',
        ),
    ]
