# Generated by Django 2.2.6 on 2020-03-22 12:15

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200321_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
