# Generated by Django 3.0.5 on 2020-05-19 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200518_1356'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
