# Generated by Django 3.0.4 on 2020-03-30 14:08

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200330_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address1',
            field=models.CharField(default=' ', max_length=1024, verbose_name='Address line 1'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address2',
            field=models.CharField(default=' ', max_length=1024, verbose_name='Address line 2'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default=' ', max_length=1024),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=django_countries.fields.CountryField(default=' ', max_length=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(default=' ', max_length=1024),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='zip_code',
            field=models.CharField(default=' ', max_length=12, verbose_name='ZIP / Postal code'),
        ),
    ]
