# Generated by Django 2.2.6 on 2020-03-22 12:15

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200322_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
