# Generated by Django 3.0.5 on 2020-05-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200504_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rate_type',
            field=models.CharField(choices=[('5 Star', '5'), ('4 Star', '4'), ('3 Star', '3'), ('2 Star', '2'), ('1 Star', '1')], default=' ', max_length=7),
        ),
    ]
