# Generated by Django 3.0.5 on 2020-05-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200505_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.TextField(max_length=600, null=True),
        ),
    ]
