# Generated by Django 3.0.4 on 2020-04-06 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200401_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='zip_code',
            field=models.CharField(default=' ', max_length=10, verbose_name='ZIP / Postal code'),
        ),
    ]
