# Generated by Django 3.0.5 on 2020-05-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200505_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('Job Post', 'Job'), ('Blog Post', 'Blog')], default=' ', max_length=9),
        ),
    ]
