# Generated by Django 3.0.4 on 2020-04-06 07:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0008_auto_20200406_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_something', models.TextField(max_length=1000, null=True)),
                ('posted_on', models.DateTimeField(default=datetime.datetime.now)),
                ('post_type', models.CharField(choices=[('Job', 'Job'), ('Blg', 'Blog')], max_length=3)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='feeds',
            field=models.ManyToManyField(blank=True, related_name='Feed', to='accounts.Post'),
        ),
    ]
