# Generated by Django 3.0.5 on 2020-05-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200505_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
