# Generated by Django 3.0.5 on 2020-05-05 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200505_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='reciever',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_recieved', to='accounts.UserProfile'),
        ),
    ]
