# Generated by Django 3.0.4 on 2020-04-06 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200406_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_profile',
            new_name='author',
        ),
    ]
