# Generated by Django 3.0.5 on 2020-05-05 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200505_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='count',
        ),
    ]
