# Generated by Django 3.0.5 on 2020-05-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_rating_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rate_type',
            field=models.CharField(choices=[('5 Star', '5 Star'), ('4 Star', '4 Star'), ('3 Star', '3 Star'), ('2 Star', '2 Star'), ('1 Star', '1 Star')], default=' ', max_length=7),
        ),
    ]
